### ISSUE TITLE
Test Fail for Chapter 8.

### ISSUE THREAD

**Issue by emilymurphy2110** [maxwelld90/tango_with_django_2_code#10]
Hello,

I have finished Chapter 8 and when doing the tests, I get 1 failure - I've been looking over the code for a couple days and can't seem to work out what I have to change. If you could help that would be great - think i'm just not understanding the error. I have included my github link if you need to look at that.

https://github.com/emilymurphy2110/TangoProject

<img width="844" alt="Screenshot 2020-02-14 at 10 22 13" src="https://user-images.githubusercontent.com/59887813/74523026-3d068880-4f14-11ea-9f46-54038f2acdb5.png">

**Comment by maxwelld90** [comment]
Hi @emilymurphy2110,

Happy to help -- you're so close! I was able to clone your repository and run your code on my computer, so thanks for making that so easy!

You have a very, very small mistake in your `category.html` template that is preventing the `<title>` tag for a category page from being produced correctly.

If I show you where the mistake is in the screenshot below, can you figure it out?

![Screenshot 2020-02-14 at 10 43 39](https://user-images.githubusercontent.com/4697501/74524470-00885c00-4f17-11ea-9fd4-fb4cbf7ec247.png)

(Look at Section 8.3, p139 of the PDF if you need some help identifying the problem)

Let me know how you get on.

Cheers!
David

**Comment by emilymurphy2110** [comment]
Thanks for your quick reply! 

Obviously not even noticed that its been missing up their and been checking the rest of my code! fixed it and all my tests pass fine now!

**Comment by maxwelld90** [comment]
💪

No worries! Cheers!
