### ISSUE TITLE
URL inconsistency in tests_chapter6

### ISSUE THREAD

**Issue by RuaridhSWilson** [maxwelld90/tango_with_django_2_code#3]
In _Creating a Population Script_ in chapter 5 of the book, the sample code gives the URL for Django Rocks as [http://www.djangorocks.com/](url), with a trailing forward slash.
![2020-01-19 19_49_55-tangowithdjango2 pdf -  Tango With Django 2  - SumatraPDF](https://user-images.githubusercontent.com/59920338/72687494-31cb6300-3af6-11ea-9fc9-719c312936ea.png)

In the `test_index_pages` method on line 108 of `tests_chapter6.py`, the index view responses are checked using regex, including a check for Django Rocks as [http://www.djangorocks.com](url), _without_ the trailing forward slash.
![2020-01-19 19_44_17-tests_chapter6 py - Visual Studio Code](https://user-images.githubusercontent.com/59920338/72687582-317f9780-3af7-11ea-9b21-df0476c0aa65.png)
This of course results in the test failing.

**Comment by maxwelld90** [comment]
Many thanks for spotting and reporting, @RuaridhSWilson -- I indeed missed a slash. Missing slashes have been added and pushed to the repository -- do a git pull and you should get the updated tests module. Cheers!
