### ISSUE TITLE
Tests at the end of chapter 4 require hard coded path to media

### ISSUE THREAD

**Issue by Apolexian** [maxwelld90/tango_with_django_2_code#4]
The required str in test_about_contains_rango: 

` required_str = f"<img src=\"{settings.MEDIA_URL}cat.jpg\" alt=\"Picture of a Cat\" />"` 

fails if about.html contains context variable like:

`<img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat.">`

only was to pass the test seems to be to hard code the path to media:
`<img src="/media/cat.jpg" alt="Picture of a Cat" />`

Not sure if this is intended or if the context variable for media should also pass the test.

**Comment by maxwelld90** [comment]
Hi @Apolexian,
Thanks for getting in touch.
I've unfortunately not been able to replicate your issue with my codebase.

In my solution, I have `<img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />` and the test passes absolutely fine.

Please make sure that you have set up your `MEDIA_URL` setting correctly.

Let me know how you get on. I'll leave this issue open until I hear from you.

**Comment by Apolexian** [comment]
Hi @maxwelld90,
Thank you for getting back to me and for leaving the issue open!

I have media configured as follows:

In settings.py 
```
MEDIA_DIR = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/media/'
```
In project level urls.py:
```
urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

```
In about.html:
```
<img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." />
```
My project structure is as follows: 
![image](https://user-images.githubusercontent.com/20223409/73083458-1f20a780-3ec3-11ea-81e8-f4ccb378a633.png)

Running the chapter 4 test using:
```
python manage.py test tests.chapter 4
```
(from project root dir)

Error message:
```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
F..................
======================================================================
FAIL: test_about_contains_cat (tests.chapter4.Chapter4ExerciseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ivan/Documents/Projects/wad2/rango/bin/tango_with_django_project/tests/chapter4.py", line 304, in test_about_contains_cat
    ), f"{FAILURE_HEADER}The HTML markup to include the image of a cat in the about template was not found. It needs to match exactly what we are looking for. Check the book.{FAILURE_FOOTER}")
AssertionError: False is not true : 


================
TwD TEST FAILURE =(
================
The HTML markup to include the image of a cat in the about template was not found. It needs to match exactly what we are looking for. Check the book.


----------------------------------------------------------------------
Ran 19 tests in 0.020s

FAILED (failures=1)
Destroying test database for alias 'default'...
```
I have included the source code of the project:
[tango_with_django_project.zip](https://github.com/maxwelld90/tango_with_django_2_code/files/4109396/tango_with_django_project.zip)

Thank you for the help!

**Comment by maxwelld90** [comment]
Thanks mate - I'll check this out when I get home this evening, I'm
currently out and about.

Is your code also up to date in your GitHub repository? I'll clone your
repository and have a look at it later if so.

Thanks,
David

**Comment by Apolexian** [comment]
Hi David,
Thank you for having the time to look at this for me, the code can be found at https://github.com/apolexian/tango_with_django_project

Have a good day
\- Ivan

**Comment by maxwelld90** [comment]
Hi @Apolexian,
Thanks for pointing me to your code! I've just cloned your repository, and installed the version of Django that your project's `settings.py` module was created with (version 2.2.3). Note that the version of Django that your `requirements.txt` file is different! This can cause major headaches, which may explain this problem.

I then downloaded my Chapter 4 tests from the sample code repo, and ran it against the latest version of your code. The result is shown below.

![test-results](https://user-images.githubusercontent.com/4697501/73113780-a6930880-3f0d-11ea-8497-0fd163e83b16.png)

All the tests pass! So I can't replicate your issue. Your code seems fine, at least on my setup.

My gut feeling that you are running a version of Django different to the version you used to create your project, and because of this, something is getting screwed up. What packages do you have installed in your environment?

Just to clarify: the test fails because `MEDIA_URL` is not resolving to anything. So there _has_ to be a configuration issue on your setup somewhere. I do not know what else it could be.

David

**Comment by Apolexian** [comment]
Hi @maxwelld90,
Thanks for getting back. The requirements.txt lists a newer version of django due to the security vuln on the version used in the environment(although I should probably just use the older version). 
The packages for the venv are as follows:
![image](https://user-images.githubusercontent.com/20223409/73113978-c4ad3880-3f0e-11ea-9a5a-70b0e0d87fbb.png)
And the version of django used is:
![image](https://user-images.githubusercontent.com/20223409/73114000-f1615000-3f0e-11ea-8ce9-35b4c30fe935.png)

The tests may pass after cloning the repo due to me including this comment in the about.html:
```
<!-- <img src="/media/cat.jpg" alt="Picture of a Cat" />  Test for chapter 4 -->
```
In order to test, apologies for that!

\- Ivan

**Comment by maxwelld90** [comment]
Hi @Apolexian,

Okay -- yeah, I see the problem now. In the example on the previous page there's a period at the end of the `alt`text, but in the exercise we were going for _no_ period at the end -- even though the sentence ends there, so there _is_ a period in the narrative. I should have wrapped it around with quote marks to demonstrate that. It's one of those things, and it's super annoying and difficult to catch them all.

Whatever, thanks for bringing this to my attention. I made the test slightly less harsh, so it accepts the string with or without a period at the end -- i.e. `Picture of a Cat` or `Picture of a Cat.`.

If you `git pull` the tests repository and run your code against the updated tests for Chapter 4, the test will now pass.

**Comment by Apolexian** [comment]
Hi @maxwelld90,
Apologies for not figuring that out! And thanks for taking the time to help me with this.
