### ISSUE TITLE
Unit test for chapter 3 require specific project name

### ISSUE THREAD

**Issue by BelfDev** [maxwelld90/tango_with_django_2_code#5]
One of the unit tests from chapter 3 requires the directory name to be exactly "tango_with_django_project". This is a bit **inconsistent** with the instructions from the book (page 27).

> This command will invoke the django-admin.py script, which will set up a new Django project called tango_with_django_project for you. Naming conventions dictate that we would typically append _project to the end of our Django project directories so we know exactly what they contain – **but naming this is really entirely up to you**.

[Unit test](https://github.com/maxwelld90/tango_with_django_2_code/blob/master/progress_tests/tests_chapter3.py) case:

```
 def test_project_created(self):
        """
        Tests whether the tango_with_django_project configuration directory is present and correct.
        """
        directory_exists = os.path.isdir(os.path.join(self.project_base_dir, 'tango_with_django_project'))
        urls_module_exists = os.path.isfile(os.path.join(self.project_base_dir, 'tango_with_django_project', 'urls.py'))
        
        self.assertTrue(directory_exists, f"{FAILURE_HEADER}Your tango_with_django_project configuration directory doesn't seem to exist. Did you use the correct name?{FAILURE_FOOTER}")
        self.assertTrue(urls_module_exists, f"{FAILURE_HEADER}Your project's urls.py module does not exist. Did you use the startproject command?{FAILURE_FOOTER}")
```

My suggestion is to remove the directory assertion and leave only the "urls_module_exists" -- adapting it to ignore the project name.

**Comment by maxwelld90** [comment]
Hi @BelfDev,

Thank you for getting in touch. I accept your comment, but what we are trying to say in the highlighted paragraph was that you don't have to comply with the _naming convention_ touched upon there -- i.e. you don't have to append `_project` to the end of the project's name.

Given that:

- the sample command above the highlighted paragraph clearly states `tango_with_django_project`;
- the narrative underneath the highlighted paragraph clearly states the creation of the `tango_with_django_project` project/directory; and
- the use of `tango_with_django_project` as the project configuration directory in paragraph at the bottom of page 27,

I'm inclined to leave things as they presently are -- notwithstanding a small revision to the book's narrative to clarify that _"but naming this is really entirely up to you"_ refers to the inclusion (or lack of) `_project` at the end of the project name. I'll push that tweak up for a future revision of the book, although this hasn't been highlighted as a problem in over five years.

Besides, if I were to remove the test you suggest, there are a series of tests later on that expect `tango_with_django_project` to be your project's name/directory anyway. So we are really gunning folk to use `tango_with_django_project` as their project name/directory!

Sorry if the text was confusing, and thanks for bringing it to our attention.

All the best,
David

**Comment by BelfDev** [comment]
Hi @maxwelld90,

Thanks for your response. I understand what you were trying to convey, but in the end, the test will still fail if the reader omits ```_project```. Perhaps nobody has highlighted this in the last five years because it's just easier to copy/paste the code snippet or rename the project :)

Thanks for writing the book! I'm enjoying it, and I thought it'd be nice to give you some input.

Best,
Pedro
