### ISSUE TITLE
Link to dashboard bootstrap HTML layout does not work

### ISSUE THREAD

**Issue by waemm** [maxwelld90/tango_with_django_2_code#7]
Hi, 

Really enjoying the book so far, I am on the bootstrap chapter, I found the link to  the modified HTML source of the dashboard link does not work. Could you please provide an alternate link ?

This is on page 163 and the link provided is: http://bit.ly/twd-bootstrap-base
Thanks

**Comment by maxwelld90** [comment]
Hi @waemm,
Thanks for your kind words!
Sorry about that. I forgot to update that link from an older version.
The correct link is: http://bit.ly/twd2-bootstrap-base-template -- I will update this in the book.

Thanks for pointing that out to me!
David

**Comment by maxwelld90** [comment]
Hey again @waemm,
Can I just check -- what date was it published on? Having looked through the markup for the Bootstrapping chapter, I can't find a link with the URL you said.

Thanks,
David

**Comment by waemm** [comment]
Hi @maxwelld90 , thanks for the fast reply, it was published on the  2019-07-30. Ah ok, I downloaded the updated version of the book and all is good! I had no idea there was an update! Just out of interest are there any major differences or things I should go back to review ?

Thanks again, it has been really enjoyable thus far!

**Comment by maxwelld90** [comment]
Hey @waemm, no worries, glad you figured it out.

The content is the same broadly. There are no major changes, or at least none that should hinder your progress -- just fixing typos, clarifying some bits here and there, and working to improve the book's content with respect to the model solution.

You should be fine -- keep going and all the best! 💪
David
